/* Generated by tools/mk_icon_assets.py - do not edit by hand.
 * Tabler Icons (MIT) baked as LV_COLOR_FORMAT_A8 glyphs and tinted at runtime.
 */
#ifndef QZDESK_ICON_ASSETS_H
#define QZDESK_ICON_ASSETS_H

#include "lvgl/lvgl.h"

typedef enum {
    QZ_ICON_ACTIVITY,
    QZ_ICON_ALERT_TRIANGLE,
    QZ_ICON_ARROW_DOWN,
    QZ_ICON_ARROW_UP,
    QZ_ICON_BATTERY_1,
    QZ_ICON_BATTERY_2,
    QZ_ICON_BATTERY_3,
    QZ_ICON_BATTERY_4,
    QZ_ICON_BATTERY_OFF,
    QZ_ICON_BELL,
    QZ_ICON_BOLT,
    QZ_ICON_BULB,
    QZ_ICON_CHART_BAR,
    QZ_ICON_CHECK,
    QZ_ICON_CHEVRON_LEFT,
    QZ_ICON_CHEVRON_RIGHT,
    QZ_ICON_CIRCLE_CHECK,
    QZ_ICON_CLOCK,
    QZ_ICON_CLOUD,
    QZ_ICON_CLOUD_FOG,
    QZ_ICON_CLOUD_RAIN,
    QZ_ICON_CLOUD_SNOW,
    QZ_ICON_CLOUD_STORM,
    QZ_ICON_CPU,
    QZ_ICON_DATABASE,
    QZ_ICON_DEVICE_DESKTOP,
    QZ_ICON_DOWNLOAD,
    QZ_ICON_DROPLET,
    QZ_ICON_EYE,
    QZ_ICON_EYE_OFF,
    QZ_ICON_FILE_TEXT,
    QZ_ICON_FOLDER,
    QZ_ICON_HELP_CIRCLE,
    QZ_ICON_HOME,
    QZ_ICON_INFO_CIRCLE,
    QZ_ICON_KEYBOARD,
    QZ_ICON_LAYOUT_GRID,
    QZ_ICON_LIST,
    QZ_ICON_MAP_PIN,
    QZ_ICON_MICROPHONE,
    QZ_ICON_PALETTE,
    QZ_ICON_PENCIL,
    QZ_ICON_PHOTO,
    QZ_ICON_PLAYER_PLAY,
    QZ_ICON_PLUG,
    QZ_ICON_PLUS,
    QZ_ICON_POWER,
    QZ_ICON_REFRESH,
    QZ_ICON_REPEAT,
    QZ_ICON_ROTATE,
    QZ_ICON_SETTINGS,
    QZ_ICON_SHIELD,
    QZ_ICON_SPARKLES,
    QZ_ICON_SUN,
    QZ_ICON_THERMOMETER,
    QZ_ICON_TIMER,
    QZ_ICON_TOOL,
    QZ_ICON_TRASH,
    QZ_ICON_USER,
    QZ_ICON_VOLUME,
    QZ_ICON_WIFI,
    QZ_ICON_WIND,
    QZ_ICON_X,
    QZ_ICON_COUNT,
} qz_icon_t;

/**
 * Glyph for `icon` at the baked size closest to `px` (never smaller than asked
 * for unless it is the largest baked size). Returns NULL for an unknown icon, so
 * callers can fall back to text.
 */
const lv_image_dsc_t *qz_icon(qz_icon_t icon, int px);

#endif
