/* Generated by tools/mk_mascot_assets.py - do not edit by hand. */
#ifndef QZDESK_MASCOT_ASSETS_H
#define QZDESK_MASCOT_ASSETS_H

#include "lvgl/lvgl.h"

/* Square size of every baked mascot image. */
#define QZ_MASCOT_SIZE 192

extern const lv_image_dsc_t qz_mascot_idle;
extern const lv_image_dsc_t qz_mascot_happy;
extern const lv_image_dsc_t qz_mascot_thinking;
extern const lv_image_dsc_t qz_mascot_confused;
extern const lv_image_dsc_t qz_mascot_speaking;
extern const lv_image_dsc_t qz_mascot_love;
extern const lv_image_dsc_t qz_mascot_blink;

#endif
